project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: assets/styles.css

website:
  title: "CartoExpert"
  navbar:
    background: "#E30F1B"
    foreground: "white"
    left:
      - text: "Accueil"
        href: index.qmd
        menu:
        - text: "Présentation du système actuel"
          href: qmd-accueil/pres_syst.qmd
        - text: "Prérequis"
          href: qmd-accueil/installations.qmd
      - text: "Regrouper et nettoyer la data"
        menu:
        - text: "Structure des fichiers .csv"
          href: instr_jeu2donnees.qmd
        - text: "Structure de la base de données Oméka S"
          href: bdd_omeka.qmd
      - text: "Base de donnée Oméka S"
        menu:
        - text: "[placeholder]"
          href: "#"
        - text: "[placeholder]"
          href: "#"
      - text: "Aides"
        menu:
        - text: "Liste des interprétations"
          href: interpretation.qmd
        - text: "DataMerge - Documentation"
          href: datamerge_use.qmd
  page-footer:
    left: "Direction de la Recherche de Paris 8"
    center: |
      <div class="footer-img">
        <img src="assets/img/logo_paris8_couleurs-officielles.png" alt="Logo de l'Université" class="footer-logo">
      </div>  
    right: "Documentation interne, ne pas diffuser"