project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: assets/styles.css

website:
  title: "CartoExpert"
  navbar:
    background: "#E30F1B"
    foreground: "white"
    left:
      - text: "General"
        menu:
        - text: "Contexte du projet"
          href: index.qmd
        - text: "Prérequis de travail"
          href: installations.qmd
        - text: "Outil DataMerge"
          href: datamerge_use.qmd
      - text: "Préparation des données"
        menu:
        - text: "Repérer, centraliser, nettoyer les données"
          href: instr_jeu2donnees.qmd
        - text: "Liste des interprétations effectuées"
          href: interpretation.qmd
        - text: "Structurer les données en CSV"
          href: newfile.qmd
      - text: "Installation technique"
        menu:
        - text: "Mettre en place Oméka S, XAMPP, etc"
          href: bdd_omeka.qmd
        - text: "Naviguer, importer et modifier sur Oméka S"
          href: newfile2.qmd
      - text: "Exploitation"
        menu:
        - text: "Présentation du système"
          href: pres_syst.qmd
        - text: "placeholder"
          href: newfile.qmd
        - text: "placeholder"
          href: newfile2.qmd


  page-footer:
    left: "Direction de la Recherche de Paris 8"
    center: |
      <div class="footer-img">
        <img src="assets/img/logo_paris8_couleurs-officielles.png" alt="Logo de l'Université" class="footer-logo">
      </div>  
    right: "Documentation interne, ne pas diffuser"