project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: assets/styles.css

website:
  title: "Cartographie des données du SVR"
  navbar:
    background: "#E30F1B"
    foreground: "white"
    left:
      - text: "Présentation du projet"
        menu:
        - text: "Contexte antérieur et actuel du projet"
          href: index.qmd
        - text: "Présentation du système actuel"
          href: pres_syst.qmd
      - text: "Prérequis pour travailler"
        href: installations.qmd
      - text: "Organisation de la data"
        menu:
        - text: "Constitution des jeux de données"
          href: instr_jeu2donnees.qmd
        - text: "La base de données Oméka S"
          href: bdd_omeka.qmd
      - text: "Aides"
        menu:
        - text: "Uniformisation des données"
          href: uniformiser.qmd
        - text: "Utiliser DataMerge.py"
          href: datamerge_use.qmd
  page-footer:
    left: "Direction de la Recherche de Paris 8"
    center: |
      <div class="footer-img">
        <img src="assets/img/logo_paris8_couleurs-officielles.png" alt="Logo de l'Université" class="footer-logo">
      </div>  
    right: "Documentation interne, ne pas diffuser"